version: '3'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    env_file: 
      - ./config/.env.dev
    logging:
      driver: awslogs
      options: 
        awslogs-group: sl-demo
        awslogs-region: us-west-2
        awslogs-stream-prefix: neo4j
  
  gql:
    container_name: sl-gql-server
    image: sagelink/sl-gql-server:latest
    build: ./sl-graphql-server
    networks:
      - default
    ports:
      - 4001:4001
      - 80:8080
    links:
      - neo4j
    depends_on:
      - neo4j
    env_file:
      - ./sl-graphql-server/.env.dev
    restart: unless-stopped
    logging:
      driver: awslogs
      options: 
        awslogs-group: sl-demo
        awslogs-region: us-west-2
        awslogs-stream-prefix: gql